[profile.default]
src     = "contracts"
test    = "contracts"
out     = "out"
libs    = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
]
solc_version = "0.8.20"

[profile.default.fuzz]
runs = 256
